"""Lead Generator Service — AI-generated investigation leads for entity drilldown.

Generates 3–7 narrative investigation leads for an entity by gathering context
from Aurora (documents, entities), Neptune (graph neighborhood, centrality),
and the existing PatternDiscoveryService, then synthesizing via Bedrock Claude.
"""

import json
import logging
import ssl
import urllib.request
import uuid
from dataclasses import dataclass, field
from typing import Any, List, Optional

logger = logging.getLogger(__name__)

BEDROCK_MODEL_ID = "anthropic.claude-3-haiku-20240307-v1:0"


# ---------------------------------------------------------------------------
# Valid lead types
# ---------------------------------------------------------------------------

VALID_LEAD_TYPES = {
    "temporal_gap",
    "cross_case_link",
    "entity_cluster",
    "document_pattern",
    "financial_anomaly",
    "geographic_convergence",
    "relationship_anomaly",
}


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------

@dataclass
class InvestigationLead:
    """A narrative-driven, actionable finding generated by the Lead Generator."""

    lead_id: str                          # UUID
    narrative: str                        # AI-generated narrative sentence
    lead_type: str                        # One of VALID_LEAD_TYPES
    confidence: float                     # 0.0–1.0
    supporting_entity_names: List[str]
    document_count: int
    date_range: Optional[str] = None      # e.g. "1945-1969"

    def to_dict(self) -> dict:
        """Serialize to a JSON-compatible dictionary."""
        return {
            "lead_id": self.lead_id,
            "narrative": self.narrative,
            "lead_type": self.lead_type,
            "confidence": self.confidence,
            "supporting_entity_names": list(self.supporting_entity_names),
            "document_count": self.document_count,
            "date_range": self.date_range,
        }


@dataclass
class EvidenceDocument:
    """A document that supports an investigation lead."""

    doc_id: str
    filename: str
    excerpt: str                          # Full text excerpt
    key_quotes: List[str]                 # Each up to 200 chars
    relevance_score: float                # 0.0–1.0


@dataclass
class EvidenceEntity:
    """An entity referenced in an evidence thread."""

    name: str
    type: str
    mention_count: int


@dataclass
class TimelineEntry:
    """A chronological event in an evidence thread."""

    date: str
    event_description: str
    source_doc: str


@dataclass
class RelationshipEdge:
    """A relationship between two entities in an evidence thread."""

    source: str
    target: str
    relationship_type: str
    weight: float


@dataclass
class EvidenceThread:
    """The collection of evidence that substantiates an InvestigationLead."""

    documents: List[EvidenceDocument] = field(default_factory=list)      # max 20
    entities: List[EvidenceEntity] = field(default_factory=list)         # max 30
    timeline: List[TimelineEntry] = field(default_factory=list)
    relationship_edges: List[RelationshipEdge] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Lead Generator Service
# ---------------------------------------------------------------------------

class LeadGeneratorService:
    """Generates 3–7 narrative investigation leads for an entity.

    Gathers context from Aurora (documents), Neptune (graph neighborhood,
    degree centrality), and optionally PatternDiscoveryService, then
    synthesizes leads via Bedrock Claude.
    """

    INVESTIGATOR_PERSONA = (
        "You are a senior federal investigative analyst with 20+ years of experience "
        "in complex multi-jurisdictional investigations. Generate narrative investigation "
        "leads that explain WHY a finding matters investigatively. Cite specific evidence "
        "documents and entity connections by name. Each lead must be actionable."
    )

    def __init__(
        self,
        aurora_cm: Any,
        bedrock_client: Any,
        neptune_endpoint: str = "",
        neptune_port: str = "8182",
        pattern_svc: Any = None,
    ) -> None:
        self._aurora = aurora_cm
        self._bedrock = bedrock_client
        self._neptune_endpoint = neptune_endpoint
        self._neptune_port = neptune_port
        self._pattern_svc = pattern_svc

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_leads(
        self,
        case_id: str,
        entity_name: str,
        entity_type: str,
        neighbors: Optional[List[dict]] = None,
        doc_excerpts: Optional[List[str]] = None,
    ) -> List[InvestigationLead]:
        """Generate 3–7 investigation leads for *entity_name*.

        Steps:
        1. Query Aurora for documents mentioning entity_name
        2. Query Neptune for 2-hop neighborhood and degree centrality
        3. If pattern_svc is available, get patterns involving this entity
        4. Build a Bedrock Claude prompt with all gathered context
        5. Parse structured JSON response into InvestigationLead objects
        6. Validate lead_type, clamp confidence, sort by confidence desc
        7. Return 3–7 leads (pad with fallback if < 3, truncate if > 7)
        """
        # 1. Aurora: documents mentioning entity
        doc_context = self._query_aurora_documents(case_id, entity_name)

        # 2. Neptune: 2-hop neighborhood + degree centrality
        graph_context = self._query_neptune_neighborhood(case_id, entity_name)

        # 3. Patterns (optional)
        pattern_context = self._query_patterns(case_id, entity_name)

        # 4–5. Build prompt and invoke Bedrock
        leads = self._generate_leads_via_bedrock(
            case_id, entity_name, entity_type,
            doc_context, graph_context, pattern_context,
            neighbors or [], doc_excerpts or [],
        )

        # On Bedrock failure, use fallback
        if not leads:
            leads = self._generate_fallback_leads(
                entity_name, entity_type,
                graph_context.get("neighbors", []),
                doc_context.get("doc_count", 0),
            )

        # 6. Validate, clamp, sort
        validated: List[InvestigationLead] = []
        for lead in leads:
            if lead.lead_type not in VALID_LEAD_TYPES:
                lead.lead_type = "document_pattern"
            lead.confidence = max(0.0, min(1.0, lead.confidence))
            validated.append(lead)

        validated.sort(key=lambda l: l.confidence, reverse=True)

        # 7. Enforce 3–7 bounds
        if len(validated) > 7:
            validated = validated[:7]
        while len(validated) < 3:
            validated.append(self._make_fallback_lead(
                entity_name, entity_type,
                doc_context.get("doc_count", 0),
                len(validated),
            ))

        return validated

    # ------------------------------------------------------------------
    # Aurora queries
    # ------------------------------------------------------------------

    def _query_aurora_documents(self, case_id: str, entity_name: str) -> dict:
        """Query Aurora for documents mentioning *entity_name*."""
        context: dict = {"doc_count": 0, "documents": [], "entity_mentions": []}
        try:
            with self._aurora.cursor() as cur:
                # Documents containing entity_name in content
                cur.execute(
                    "SELECT document_id, source_filename, LEFT(raw_text, 500) "
                    "FROM documents WHERE case_file_id = %s "
                    "AND raw_text ILIKE %s "
                    "ORDER BY indexed_at DESC LIMIT 20",
                    (case_id, f"%{entity_name}%"),
                )
                rows = cur.fetchall()
                context["doc_count"] = len(rows)
                for row in rows:
                    context["documents"].append({
                        "doc_id": row[0],
                        "filename": row[1],
                        "excerpt": row[2] or "",
                    })

                # Entity occurrence count
                try:
                    cur.execute(
                        "SELECT canonical_name, entity_type, occurrence_count "
                        "FROM entities WHERE case_file_id = %s "
                        "AND canonical_name ILIKE %s "
                        "ORDER BY occurrence_count DESC LIMIT 10",
                        (case_id, f"%{entity_name}%"),
                    )
                    for erow in cur.fetchall():
                        context["entity_mentions"].append({
                            "name": erow[0],
                            "type": erow[1],
                            "count": erow[2],
                        })
                except Exception:
                    pass  # entities table may not exist
        except Exception as e:
            logger.error("Aurora document query failed for '%s': %s", entity_name, str(e)[:200])
        return context

    # ------------------------------------------------------------------
    # Neptune queries
    # ------------------------------------------------------------------

    def _query_neptune_neighborhood(self, case_id: str, entity_name: str) -> dict:
        """Query Neptune for 2-hop neighborhood and degree centrality."""
        context: dict = {"neighbors": [], "degree": 0, "hop2_count": 0}
        if not self._neptune_endpoint:
            return context

        label = f"Entity_{case_id}"
        url = f"https://{self._neptune_endpoint}:{self._neptune_port}/gremlin"
        ctx = ssl.create_default_context()

        def _gremlin(query: str, timeout: int = 30) -> list:
            data = json.dumps({"gremlin": query}).encode("utf-8")
            req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
            with urllib.request.urlopen(req, context=ctx, timeout=timeout) as resp:
                body = json.loads(resp.read().decode("utf-8"))
            raw = body.get("result", {}).get("data", {})
            if isinstance(raw, dict) and "@value" in raw:
                raw = raw["@value"]
            return raw if isinstance(raw, list) else []

        def _unwrap(val):
            if isinstance(val, dict):
                if val.get("@type") == "g:Map" and "@value" in val:
                    flat = val["@value"]
                    if isinstance(flat, list):
                        return {flat[i]: _unwrap(flat[i + 1]) for i in range(0, len(flat) - 1, 2)}
                if "@value" in val:
                    return _unwrap(val["@value"])
            return val

        try:
            esc = entity_name.replace("'", "\\'")

            # 1-hop neighbors with type
            q_neighbors = (
                f"g.V().hasLabel('{label}').has('canonical_name','{esc}')"
                f".bothE().limit(200).otherV().hasLabel('{label}').dedup().limit(50)"
                f".project('n','t').by('canonical_name').by('entity_type')"
            )
            raw = _gremlin(q_neighbors, timeout=25)
            for r in raw:
                parsed = _unwrap(r)
                if isinstance(parsed, dict) and parsed.get("n"):
                    n = _unwrap(parsed["n"]) if isinstance(parsed["n"], dict) else parsed["n"]
                    t = _unwrap(parsed["t"]) if isinstance(parsed.get("t"), dict) else parsed.get("t", "unknown")
                    context["neighbors"].append({"name": n, "type": t})

            # Degree centrality
            q_degree = (
                f"g.V().hasLabel('{label}').has('canonical_name','{esc}')"
                f".bothE().count()"
            )
            deg_raw = _gremlin(q_degree, timeout=10)
            if deg_raw:
                deg_val = _unwrap(deg_raw[0]) if isinstance(deg_raw[0], dict) else deg_raw[0]
                context["degree"] = int(deg_val) if deg_val else 0

            # 2-hop count (approximate)
            q_hop2 = (
                f"g.V().hasLabel('{label}').has('canonical_name','{esc}')"
                f".both().both().dedup().count()"
            )
            hop2_raw = _gremlin(q_hop2, timeout=15)
            if hop2_raw:
                hop2_val = _unwrap(hop2_raw[0]) if isinstance(hop2_raw[0], dict) else hop2_raw[0]
                context["hop2_count"] = int(hop2_val) if hop2_val else 0

        except Exception as e:
            logger.error("Neptune neighborhood query failed for '%s': %s", entity_name, str(e)[:200])

        return context

    # ------------------------------------------------------------------
    # Pattern queries
    # ------------------------------------------------------------------

    def _query_patterns(self, case_id: str, entity_name: str) -> List[dict]:
        """Get patterns involving *entity_name* from PatternDiscoveryService."""
        if not self._pattern_svc:
            return []
        try:
            report = self._pattern_svc.discover_top_patterns(case_id)
            patterns = report.get("patterns", [])
            # Filter to patterns that mention this entity
            relevant = []
            for p in patterns:
                entities = p.get("entities", [])
                entity_names_in_pattern = [
                    e.get("name", "") if isinstance(e, dict) else str(e)
                    for e in entities
                ]
                if any(entity_name.lower() in n.lower() for n in entity_names_in_pattern):
                    relevant.append(p)
            return relevant
        except Exception as e:
            logger.error("Pattern query failed for '%s': %s", entity_name, str(e)[:200])
            return []

    # ------------------------------------------------------------------
    # Bedrock lead generation
    # ------------------------------------------------------------------

    def _generate_leads_via_bedrock(
        self,
        case_id: str,
        entity_name: str,
        entity_type: str,
        doc_context: dict,
        graph_context: dict,
        pattern_context: List[dict],
        neighbors: List[dict],
        doc_excerpts: List[str],
    ) -> List[InvestigationLead]:
        """Build prompt, invoke Bedrock, parse response into leads."""
        # Build context summary for the prompt
        neighbor_names = [n.get("name", "") for n in graph_context.get("neighbors", [])]
        if neighbors:
            neighbor_names.extend(n.get("name", "") for n in neighbors if n.get("name"))
        neighbor_names = list(set(neighbor_names))[:30]

        doc_summaries = []
        for d in doc_context.get("documents", [])[:10]:
            doc_summaries.append(f"- {d['filename']}: {d['excerpt'][:200]}")
        if doc_excerpts:
            for exc in doc_excerpts[:5]:
                doc_summaries.append(f"- (provided): {exc[:200]}")

        pattern_summaries = []
        for p in pattern_context[:5]:
            q = p.get("question", p.get("description", ""))
            if q:
                pattern_summaries.append(f"- {q}")

        prompt = (
            f"Analyze the following investigative context for entity '{entity_name}' "
            f"(type: {entity_type}) in case {case_id}.\n\n"
            f"GRAPH CONTEXT:\n"
            f"- Degree centrality: {graph_context.get('degree', 0)} direct connections\n"
            f"- 2-hop reach: {graph_context.get('hop2_count', 0)} entities within 2 hops\n"
            f"- Key neighbors: {', '.join(neighbor_names[:15]) if neighbor_names else 'none found'}\n\n"
            f"DOCUMENT CONTEXT ({doc_context.get('doc_count', 0)} documents):\n"
            f"{chr(10).join(doc_summaries[:10]) if doc_summaries else 'No documents found.'}\n\n"
        )
        if pattern_summaries:
            prompt += f"DISCOVERED PATTERNS:\n{chr(10).join(pattern_summaries)}\n\n"

        prompt += (
            "Generate 3 to 7 investigation leads as a JSON array. Each lead must explain "
            "WHY the finding matters investigatively — not just state graph metrics.\n\n"
            "Return ONLY a JSON array with objects containing these fields:\n"
            '- "narrative": a sentence explaining the investigative significance\n'
            '- "lead_type": one of [temporal_gap, cross_case_link, entity_cluster, '
            'document_pattern, financial_anomaly, geographic_convergence, relationship_anomaly]\n'
            '- "confidence": float 0.0-1.0 based on evidence strength\n'
            '- "supporting_entity_names": array of entity names supporting this lead\n'
            '- "document_count": integer count of relevant documents\n'
            '- "date_range": string like "1945-1969" or null\n\n'
            "Return ONLY the JSON array, no other text."
        )

        try:
            response = self._bedrock.invoke_model(
                modelId=BEDROCK_MODEL_ID,
                contentType="application/json",
                accept="application/json",
                body=json.dumps({
                    "anthropic_version": "bedrock-2023-05-31",
                    "max_tokens": 2000,
                    "system": self.INVESTIGATOR_PERSONA,
                    "messages": [{"role": "user", "content": prompt}],
                }),
            )
            body = json.loads(response["body"].read())
            text = body.get("content", [{}])[0].get("text", "")
        except Exception as e:
            logger.error("Bedrock invocation failed for lead generation: %s", str(e)[:200])
            return []

        if not text:
            return []

        return self._parse_leads_response(text, entity_name)

    def _parse_leads_response(self, text: str, entity_name: str) -> List[InvestigationLead]:
        """Parse Bedrock JSON response into InvestigationLead objects."""
        # Extract JSON array from response (may have surrounding text)
        start = text.find("[")
        end = text.rfind("]")
        if start == -1 or end == -1 or end <= start:
            logger.error("Could not find JSON array in Bedrock response")
            return []

        try:
            items = json.loads(text[start:end + 1])
        except json.JSONDecodeError as e:
            logger.error("Failed to parse Bedrock JSON response: %s", str(e)[:200])
            return []

        if not isinstance(items, list):
            return []

        leads: List[InvestigationLead] = []
        for item in items:
            if not isinstance(item, dict):
                continue
            narrative = item.get("narrative", "")
            if not narrative:
                continue

            supporting = item.get("supporting_entity_names", [])
            if not isinstance(supporting, list):
                supporting = []
            supporting = [str(s) for s in supporting if s]

            leads.append(InvestigationLead(
                lead_id=str(uuid.uuid4()),
                narrative=str(narrative),
                lead_type=str(item.get("lead_type", "document_pattern")),
                confidence=float(item.get("confidence", 0.5)),
                supporting_entity_names=supporting,
                document_count=int(item.get("document_count", 0)),
                date_range=item.get("date_range"),
            ))

        return leads

    # ------------------------------------------------------------------
    # Fallback leads
    # ------------------------------------------------------------------

    def _generate_fallback_leads(
        self,
        entity_name: str,
        entity_type: str,
        neighbors: list,
        doc_count: int,
    ) -> List[InvestigationLead]:
        """Generate 2+ fallback leads from graph statistics with narrative framing.

        Called when Bedrock invocation fails. Uses the neighbors list and
        doc_count to build meaningful investigative narratives rather than
        raw graph metrics.
        """
        leads: List[InvestigationLead] = []

        # Derive neighbor names for narrative use
        neighbor_names = [
            n.get("name", "") if isinstance(n, dict) else str(n)
            for n in (neighbors or [])
        ]
        neighbor_names = [n for n in neighbor_names if n]

        # --- Lead 1: Entity cluster / relationship analysis ---
        if neighbor_names:
            sample = neighbor_names[:5]
            sample_str = ", ".join(sample)
            extra = f" and {len(neighbor_names) - len(sample)} others" if len(neighbor_names) > len(sample) else ""
            narrative = (
                f"{entity_name} ({entity_type}) is connected to {len(neighbor_names)} entities "
                f"including {sample_str}{extra} — this entity cluster warrants deeper investigation "
                f"into shared document appearances"
            )
            leads.append(InvestigationLead(
                lead_id=str(uuid.uuid4()),
                narrative=narrative,
                lead_type="entity_cluster",
                confidence=min(0.7, 0.3 + len(neighbor_names) * 0.02),
                supporting_entity_names=[entity_name] + sample,
                document_count=doc_count,
                date_range=None,
            ))
        else:
            # No neighbors — still produce a relationship anomaly lead
            narrative = (
                f"{entity_name} ({entity_type}) has no known graph connections "
                f"— this isolation is itself an anomaly worth investigating, as it may indicate "
                f"incomplete data ingestion or a deliberately obscured relationship network"
            )
            leads.append(InvestigationLead(
                lead_id=str(uuid.uuid4()),
                narrative=narrative,
                lead_type="relationship_anomaly",
                confidence=0.4,
                supporting_entity_names=[entity_name],
                document_count=doc_count,
                date_range=None,
            ))

        # --- Lead 2: Document pattern / temporal analysis ---
        if doc_count > 0:
            narrative = (
                f"{entity_name} appears in {doc_count} document{'s' if doc_count != 1 else ''} "
                f"— temporal analysis of these appearances may reveal gaps or patterns "
                f"in the documentary record"
            )
            leads.append(InvestigationLead(
                lead_id=str(uuid.uuid4()),
                narrative=narrative,
                lead_type="document_pattern",
                confidence=min(0.65, 0.25 + doc_count * 0.03),
                supporting_entity_names=[entity_name],
                document_count=doc_count,
                date_range=None,
            ))
        else:
            narrative = (
                f"{entity_name} ({entity_type}) does not appear in any ingested documents "
                f"— this absence from the documentary record despite graph presence suggests "
                f"the entity may be referenced indirectly or under alternate names"
            )
            leads.append(InvestigationLead(
                lead_id=str(uuid.uuid4()),
                narrative=narrative,
                lead_type="temporal_gap",
                confidence=0.45,
                supporting_entity_names=[entity_name],
                document_count=0,
                date_range=None,
            ))

        # --- Lead 3 (bonus): Cross-reference lead when both neighbors and docs exist ---
        if neighbor_names and doc_count > 0:
            top_neighbors = neighbor_names[:3]
            narrative = (
                f"{entity_name} co-occurs with {', '.join(top_neighbors)} across {doc_count} "
                f"document{'s' if doc_count != 1 else ''} — cross-referencing these connections "
                f"may surface undisclosed relationships or coordinated activity patterns"
            )
            leads.append(InvestigationLead(
                lead_id=str(uuid.uuid4()),
                narrative=narrative,
                lead_type="cross_case_link",
                confidence=min(0.6, 0.2 + len(neighbor_names) * 0.015 + doc_count * 0.02),
                supporting_entity_names=[entity_name] + top_neighbors,
                document_count=doc_count,
                date_range=None,
            ))

        return leads

    def _make_fallback_lead(
        self,
        entity_name: str,
        entity_type: str,
        doc_count: int,
        index: int,
    ) -> InvestigationLead:
        """Create a single padding lead to meet the 3-lead minimum."""
        fallback_types = ["document_pattern", "entity_cluster", "relationship_anomaly"]
        lead_type = fallback_types[index % len(fallback_types)]
        return InvestigationLead(
            lead_id=str(uuid.uuid4()),
            narrative=(
                f"{entity_name} ({entity_type}) appears across {doc_count} documents "
                f"— further investigation recommended to identify {lead_type.replace('_', ' ')} patterns."
            ),
            lead_type=lead_type,
            confidence=0.3,
            supporting_entity_names=[entity_name],
            document_count=doc_count,
            date_range=None,
        )
