"""Data models for Investigative Signal Mining.

Defines dataclasses for IoV taxonomy structures, scoring results,
findings, drill-down results, and investigator search directives.
No bulk processing, no EC2, no Bedrock calls — pure data structures.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class FlatIndicator:
    """A single IoV indicator flattened from the hierarchy tree.

    Attributes:
        indicator_text: The indicator description string.
        category_path: Full path from root, e.g. ["Exclusionary Conduct", "Technological Lockout"].
        depth: 0 = top-level category, 1 = sub_category, etc.
        weight: Scoring weight based on depth (1.0 for depth 0, 0.7 for depth 1, 0.5 for depth 2).
    """

    indicator_text: str
    category_path: list[str]
    depth: int
    weight: float


@dataclass
class ScoringResult:
    """Result of scoring a finding against the IoV hierarchy.

    Attributes:
        score: Composite signal strength 0-100.
        tier: Classification tier — "HIGH", "MEDIUM", or "LOW".
        matched_indicators: List of FlatIndicator objects that matched.
        category_breakdown: Dict mapping category name to match count.
        corroboration_applied: True if the corroboration multiplier was used.
    """

    score: int
    tier: str
    matched_indicators: list[FlatIndicator]
    category_breakdown: dict[str, int]
    corroboration_applied: bool


@dataclass
class IovHierarchy:
    """Parsed IoV taxonomy hierarchy for a case type.

    Attributes:
        case_type: The antitrust case type (e.g. "monopolization").
        version: Semantic version of this hierarchy config.
        categories: List of category dicts with name, indicators, optional sub_categories.
    """

    case_type: str
    version: str
    categories: list[dict]


@dataclass
class Finding:
    """A discrete investigative finding with signal strength score.

    Attributes:
        finding_id: UUID primary key.
        lead_id: UUID of the parent pre-case lead.
        parent_finding_id: UUID of parent finding (None for top-level).
        summary: 2-line summary of what was found.
        source_url: Link to the source data.
        signal_strength: Score 0-100.
        tier: "HIGH", "MEDIUM", or "LOW".
        matched_indicators: JSON-serializable list of matched indicator dicts.
        drill_down_depth: 0 for top-level, 1-3 for sub-findings.
        created_at: Timestamp of creation.
        raw_data: Full OSINT response data as dict.
        sub_findings: Nested child findings (populated on retrieval).
        directive_text: Original investigator directive if from search.
    """

    finding_id: str
    lead_id: str
    parent_finding_id: Optional[str] = None
    summary: str = ""
    source_url: str = ""
    signal_strength: int = 0
    tier: str = "LOW"
    matched_indicators: list[dict] = field(default_factory=list)
    drill_down_depth: int = 0
    created_at: Optional[datetime] = None
    raw_data: dict = field(default_factory=dict)
    sub_findings: list["Finding"] = field(default_factory=list)
    directive_text: Optional[str] = None
    is_alert: bool = False
    alert_dismissed: bool = False

    def to_dict(self) -> dict:
        """Serialize to JSON-compatible dict for API responses."""
        return {
            "finding_id": self.finding_id,
            "lead_id": self.lead_id,
            "parent_finding_id": self.parent_finding_id,
            "summary": self.summary,
            "source_url": self.source_url,
            "signal_strength": self.signal_strength,
            "tier": self.tier,
            "matched_indicators": self.matched_indicators,
            "drill_down_depth": self.drill_down_depth,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "directive_text": self.directive_text,
            "is_alert": self.is_alert,
            "alert_dismissed": self.alert_dismissed,
            "sub_findings": [sf.to_dict() for sf in self.sub_findings],
        }


@dataclass
class FollowUpQuery:
    """A structured follow-up query generated by the drill-down engine.

    Attributes:
        target_source: OSINT source to query (e.g. "sec_edgar", "news_press").
        search_terms: Search terms or keywords.
        rationale: Why this query is relevant to the finding.
    """

    target_source: str
    search_terms: str
    rationale: str


@dataclass
class DrillDownResult:
    """Result of a drill-down cycle on a finding.

    Attributes:
        parent_finding_id: UUID of the finding that was drilled into.
        sub_findings: List of new findings discovered.
        queries_generated: Number of follow-up queries generated by AI.
        queries_executed: Number of queries actually executed.
        depth_reached: The drill-down depth of this cycle.
        status: "completed", "uncorroborated", or "depth_limit_reached".
    """

    parent_finding_id: str
    sub_findings: list[Finding] = field(default_factory=list)
    queries_generated: int = 0
    queries_executed: int = 0
    depth_reached: int = 0
    status: str = "completed"

    def to_dict(self) -> dict:
        """Serialize to JSON-compatible dict for API responses."""
        return {
            "parent_finding_id": self.parent_finding_id,
            "sub_findings": [f.to_dict() for f in self.sub_findings],
            "queries_generated": self.queries_generated,
            "queries_executed": self.queries_executed,
            "depth_reached": self.depth_reached,
            "status": self.status,
        }


@dataclass
class ParsedDirective:
    """Structured search parameters parsed from a natural language directive.

    Attributes:
        persons: List of person names mentioned.
        organizations: List of organization names mentioned.
        document_types: List of document types (e.g. "PACER filings", "Form 990s").
        geographic_regions: List of geographic areas mentioned.
        target_sources: List of OSINT source identifiers to query.
        raw_directive: The original directive text.
    """

    persons: list[str] = field(default_factory=list)
    organizations: list[str] = field(default_factory=list)
    document_types: list[str] = field(default_factory=list)
    geographic_regions: list[str] = field(default_factory=list)
    target_sources: list[str] = field(default_factory=list)
    raw_directive: str = ""


@dataclass
class DirectiveResult:
    """Result of executing an investigator search directive.

    Attributes:
        findings: List of findings produced by the directive.
        directive_text: The original directive string.
        unsupported_sources: List of sources that couldn't be queried.
    """

    findings: list[Finding] = field(default_factory=list)
    directive_text: str = ""
    unsupported_sources: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        """Serialize to JSON-compatible dict for API responses."""
        return {
            "findings": [f.to_dict() for f in self.findings],
            "directive_text": self.directive_text,
            "unsupported_sources": self.unsupported_sources,
        }


@dataclass
class PaginatedFindings:
    """Paginated response for findings retrieval.

    Attributes:
        findings: List of top-level findings (with nested sub_findings).
        total_count: Total number of top-level findings for the lead.
        page: Current page number (1-indexed).
        page_size: Number of items per page.
        total_pages: Total number of pages.
    """

    findings: list[Finding] = field(default_factory=list)
    total_count: int = 0
    page: int = 1
    page_size: int = 25
    total_pages: int = 0

    def to_dict(self) -> dict:
        """Serialize to JSON-compatible dict for API responses."""
        return {
            "findings": [f.to_dict() for f in self.findings],
            "total_count": self.total_count,
            "page": self.page,
            "page_size": self.page_size,
            "total_pages": self.total_pages,
        }


class IovConfigError(Exception):
    """Raised when IoV taxonomy configuration is invalid or missing."""

    def __init__(self, case_type: str, message: str) -> None:
        self.case_type = case_type
        self.message = message
        super().__init__(f"IoV config error for '{case_type}': {message}")
